export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST'
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS'
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE'

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE'